<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Fotos para todos</title>
<link rel="stylesheet" href="css/print.css" media="print" />
<link rel="stylesheet" href="css/general.css" media="screen"/>
<link rel="stylesheet" href="css/color_principal.css" media="screen" title="Principal"/>
<link rel="stylesheet alternate" href="css/color_alternativo.css" media="screen" title="Alternativo" disabled="true" />
<link rel="stylesheet" href="css/responsive_small.css" media="screen and (max-width:940px)" />
<link rel="stylesheet" href="css/responsive_big.css" media="screen and (min-width:939px)" />
<script src="js/validation.js"></script>
<script src="js/style_change.js"></script>
</head>
<body onLoad="retrieveAndSetStyle()" onUnload="saveStyle()">